title: Your name or name of site
description: A website with a blog
footer_text: Copyright 2020 Your name
header_feature_image: ../uploads/boat-on-the-horizon-photo-by-claudia-altamimi-on-unsplash-.jpg
header_text: My Dream Blog
header_text_color: "#ffffff"
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
