title: Nicolle Hunter
description: A website with a blog
footer_text: Copyright 2021 Nicolle Hunter
header_feature_image: ../uploads/lightning-over-waterfall-photo-by-sean-pierce-on-unsplash-.jpg
header_text: Little Pinch of Soul
header_text_color: "#ffffff"
bannerheight: 20vmax
logo: ../uploads/animated-girl-with-sunflowers.png
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
