title: Nicolle Hunter
description: A website with a blog
footer_text: Copyright 2021 Nicolle Hunter
header_feature_image: ../uploads/boat-on-the-horizon-photo-by-claudia-altamimi-on-unsplash-.jpg
header_text: Little Pinch of Soul
header_text_color: "#ffffff"
bannerheight: 20vmax
logo: ../uploads/slay-queen-scrabble-words-photo-by-sincerely-media-on-unsplash-.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
