title: Nicolle Hunter
description: A website with a blog
footer_text: Copyright 2021 Nicolle Hunter
header_feature_image: ../uploads/placeholder3.jpg
header_text: "Little Pinch of Soul "
header_text_color: "#000000"
bannerheight: 40vmax
logo: ../uploads/animated-girl-with-sunflowers.png
favicon: ../uploads/animated-girl-with-sunflowers.png
gridlayout: false
fixednavbar: false
upzoom: true
